### ISSUE TITLE
Communicate game ending better

### ISSUE THREAD

**Issue by simonhackler** [bromberry-games/Inkvestigations#233]

**Comment by zivky** [comment]
@simonhackler 
Maybe something like this as ending animation: https://design.penpot.app/#/workspace/b4857f34-a0e5-81ae-8003-565604ec74e6/43442e9d-d45f-8169-8003-fae1d2db2fb7?page-id=43442e9d-d45f-8169-8003-fae1d2db2fb8&layout=layers
