### ISSUE TITLE
Prison breaks on phone

### ISSUE THREAD

**Issue by zivky** [bromberry-games/Inkvestigations#273]
Played on android phone. What happened:

1. I started Prison and first message was something it had info about and it worked fine
2. Second message was some made up info, it started generating and seemed to stop when the event occurred
3. It only let me regenerate, which I tried once but it didn't work
4. I reloaded the page and it went blank
5. page shows "array contains an empty element at index 8"

**Comment by simonhackler** [comment]
fixed
